import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class SeedHomePage extends StatelessWidget {
  const SeedHomePage({super.key});

  Future<void> seedStudents() async {
    final CollectionReference students = FirebaseFirestore.instance.collection('students');

    for (var student in studentData) {
      await students.doc(student['rollNo']).set(student);
    }

    print("✅ Seed data uploaded to Firestore.");
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Seed Firestore")),
      body: Center(
        child: ElevatedButton(
          onPressed: () async {
            await seedStudents();
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Seeded student data to Firestore')),
            );
          },
          child: const Text("Seed Students to Firestore"),
        ),
      ),
    );
  }
}

final List<Map<String, dynamic>> studentData = [
  {
    "name": "Arjun Verma",
    "age": 21,
    "rollNo": "1023CSEA56",
    "email": "arjun.verma@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "92%",
    "lastReleasedResult": 9.2,
    "totalCGPA": 8.8,
    "degreeName": "BE",
    "departmentName": "Computer Science",
    "year": "3",
    "semester": "6",
  },
  {
    "name": "Meera Iyer",
    "age": 22,
    "rollNo": "1024ECEB43",
    "email": "meera.iyer@example.com",
    "feesStatus": "Unpaid",
    "attendanceStatus": "85%",
    "lastReleasedResult": 8.1,
    "totalCGPA": 7.9,
    "degreeName": "BE",
    "departmentName": "Electronics",
    "year": "4",
    "semester": "7",
  },
  {
    "name": "Ravi Kumar",
    "age": 19,
    "rollNo": "1035MECA12",
    "email": "ravi.kumar@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "75%",
    "lastReleasedResult": 6.8,
    "totalCGPA": 7.1,
    "degreeName": "BE",
    "departmentName": "Mechanical",
    "year": "2",
    "semester": "3",
  },
  {
    "name": "Sneha Reddy",
    "age": 24,
    "rollNo": "1042ITBA98",
    "email": "sneha.reddy@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "96%",
    "lastReleasedResult": 9.5,
    "totalCGPA": 9.0,
    "degreeName": "BE",
    "departmentName": "Information Tech",
    "year": "4",
    "semester": "8",
  },
  {
    "name": "Tarun Das",
    "age": 20,
    "rollNo": "1056CEEB56",
    "email": "tarun.das@example.com",
    "feesStatus": "Unpaid",
    "attendanceStatus": "66%",
    "lastReleasedResult": 5.9,
    "totalCGPA": 6.3,
    "degreeName": "BE",
    "departmentName": "Civil",
    "year": "2",
    "semester": "4",
  },
  {
    "name": "Neha Kapoor",
    "age": 21,
    "rollNo": "1067CSEA76",
    "email": "neha.kapoor@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "89%",
    "lastReleasedResult": 8.7,
    "totalCGPA": 8.5,
    "degreeName": "BE",
    "departmentName": "Computer Science",
    "year": "3",
    "semester": "5",
  },
  {
    "name": "Akash Menon",
    "age": 23,
    "rollNo": "1078MECHR21",
    "email": "akash.menon@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "91%",
    "lastReleasedResult": 8.2,
    "totalCGPA": 8.0,
    "degreeName": "BE",
    "departmentName": "Mechanical",
    "year": "4",
    "semester": "7",
  },
  {
    "name": "Riya Sen",
    "age": 20,
    "rollNo": "1081ECEK12",
    "email": "riya.sen@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "87%",
    "lastReleasedResult": 7.9,
    "totalCGPA": 8.1,
    "degreeName": "BE",
    "departmentName": "Electronics",
    "year": "3",
    "semester": "6",
  },
  {
    "name": "Vikram Singh",
    "age": 22,
    "rollNo": "1094CHEB23",
    "email": "vikram.singh@example.com",
    "feesStatus": "Unpaid",
    "attendanceStatus": "72%",
    "lastReleasedResult": 6.4,
    "totalCGPA": 6.8,
    "degreeName": "BE",
    "departmentName": "Chemical",
    "year": "4",
    "semester": "8",
  },
  {
    "name": "Aditi Nair",
    "age": 19,
    "rollNo": "1105ITCA65",
    "email": "aditi.nair@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "90%",
    "lastReleasedResult": 9.1,
    "totalCGPA": 8.9,
    "degreeName": "BE",
    "departmentName": "Information Tech",
    "year": "2",
    "semester": "4",
  },
  {
    "name": "Rohit Sharma",
    "age": 25,
    "rollNo": "1201PHDA01",
    "email": "rohit.sharma@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "95%",
    "lastReleasedResult": 9.7,
    "totalCGPA": 9.4,
    "degreeName": "PhD",
    "departmentName": "Computer Science",
    "year": "",
    "semester": "",
  },
  {
    "name": "Kavya Balan",
    "age": 21,
    "rollNo": "1123CSEB55",
    "email": "kavya.balan@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "84%",
    "lastReleasedResult": 7.5,
    "totalCGPA": 8.0,
    "degreeName": "BE",
    "departmentName": "Computer Science",
    "year": "3",
    "semester": "5",
  },
  {
    "name": "Aman Joshi",
    "age": 24,
    "rollNo": "1134ECEP32",
    "email": "aman.joshi@example.com",
    "feesStatus": "Unpaid",
    "attendanceStatus": "79%",
    "lastReleasedResult": 6.7,
    "totalCGPA": 7.2,
    "degreeName": "BE",
    "departmentName": "Electronics",
    "year": "4",
    "semester": "8",
  },
  {
    "name": "Shreya Ghosh",
    "age": 22,
    "rollNo": "1146MECD18",
    "email": "shreya.ghosh@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "94%",
    "lastReleasedResult": 9.0,
    "totalCGPA": 8.7,
    "degreeName": "BE",
    "departmentName": "Mechanical",
    "year": "4",
    "semester": "7",
  },
  {
    "name": "Nikhil Rao",
    "age": 20,
    "rollNo": "1157CSEC90",
    "email": "nikhil.rao@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "86%",
    "lastReleasedResult": 8.4,
    "totalCGPA": 8.2,
    "degreeName": "BE",
    "departmentName": "Computer Science",
    "year": "3",
    "semester": "6",
  },
  {
    "name": "Priya Sharma",
    "age": 19,
    "rollNo": "1169ECED44",
    "email": "priya.sharma@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "93%",
    "lastReleasedResult": 9.3,
    "totalCGPA": 9.1,
    "degreeName": "BE",
    "departmentName": "Electronics",
    "year": "2",
    "semester": "3",
  },
  {
    "name": "Surya Narain",
    "age": 22,
    "rollNo": "1178CEEB61",
    "email": "surya.narain@example.com",
    "feesStatus": "Unpaid",
    "attendanceStatus": "70%",
    "lastReleasedResult": 5.8,
    "totalCGPA": 6.5,
    "degreeName": "BE",
    "departmentName": "Civil",
    "year": "4",
    "semester": "8",
  },
  {
    "name": "Devika Patel",
    "age": 21,
    "rollNo": "1183ITFB23",
    "email": "devika.patel@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "92%",
    "lastReleasedResult": 8.9,
    "totalCGPA": 8.6,
    "degreeName": "BE",
    "departmentName": "Information Tech",
    "year": "3",
    "semester": "6",
  },
  {
    "name": "Varun Mehta",
    "age": 24,
    "rollNo": "1195PHDC92",
    "email": "varun.mehta@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "97%",
    "lastReleasedResult": 9.6,
    "totalCGPA": 9.3,
    "degreeName": "PhD",
    "departmentName": "Mechanical",
    "year": "",
    "semester": "",
  },
  {
    "name": "Ishita Jain",
    "age": 20,
    "rollNo": "1207MEAA11",
    "email": "ishita.jain@example.com",
    "feesStatus": "Paid",
    "attendanceStatus": "88%",
    "lastReleasedResult": 8.5,
    "totalCGPA": 8.3,
    "degreeName": "BE",
    "departmentName": "Mechanical",
    "year": "3",
    "semester": "5",
  },
];
