name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"  # replace with your version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or any version you used for firebase-admin

      - name: Install Node packages
        run: npm install
        working-directory: lib/add_emails

      - name: Build release APK
        run: flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
